### ISSUE TITLE
Config file broken in 1.18.2

### ISSUE THREAD

**Issue by xelotex** [Rikurob/Vmh#1]
Version 1.18.2 seems to have a broken config or something. (in game) When i try to configure entity black/white lists, the letters appear in red and doesn't let me save any changes. When i go to the config file and save changes, then launch the game, it crashes.
[crash-2023-08-09_16.12.52-client.txt](https://github.com/Rikurob/Vmh/files/12307393/crash-2023-08-09_16.12.52-client.txt)

**Comment by Rikurob** [comment]
Are you sure you entered everything correctly, can you share the config file? Either way it will change alot very soon for 1.18.2, 1.19.2+ already has.
